# Generated by Django 4.2.7 on 2025-12-01 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome attività"),
                ),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Admin"),
                            ("admin", "Admin"),
                            ("base", "Volontario Base"),
                        ],
                        max_length=50,
                        verbose_name="Area di competenza",
                    ),
                ),
                (
                    "colore_hex",
                    models.CharField(
                        default="#1976d2",
                        help_text="Colore per visualizzazione calendario (es. #FF5733)",
                        max_length=7,
                        verbose_name="Colore",
                    ),
                ),
                (
                    "link_iscrizione",
                    models.URLField(
                        blank=True,
                        help_text="Link esterno per iscrizione (es. Google Form)",
                        null=True,
                        verbose_name="Link iscrizione predefinito",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Attivo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eliminato il"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attività",
                "verbose_name_plural": "Attività",
                "ordering": ["area", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titolo",
                    models.CharField(max_length=200, verbose_name="Titolo turno"),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("ora_inizio", models.TimeField(verbose_name="Ora inizio")),
                ("ora_fine", models.TimeField(verbose_name="Ora fine")),
                (
                    "posti_disponibili",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Numero di volontari richiesti (0 = illimitato)",
                        verbose_name="Posti disponibili",
                    ),
                ),
                (
                    "link_iscrizione",
                    models.URLField(
                        blank=True,
                        help_text="Link specifico per questo turno (sovrascrive quello dell'attività)",
                        null=True,
                        verbose_name="Link iscrizione",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("is_active", models.BooleanField(default=True, verbose_name="Attivo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eliminato il"
                    ),
                ),
                (
                    "attivita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turni",
                        to="activities.activity",
                        verbose_name="Attività",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shifts_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turni",
                "ordering": ["data", "ora_inizio"],
            },
        ),
        migrations.CreateModel(
            name="ShiftEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In attesa"),
                            ("confirmed", "Confermato"),
                            ("cancelled", "Annullato"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "note_volontario",
                    models.TextField(blank=True, verbose_name="Note del volontario"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iscritto il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eliminato il"
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iscrizioni",
                        to="activities.shift",
                        verbose_name="Turno",
                    ),
                ),
                (
                    "volontario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iscrizioni_turni",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Volontario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Iscrizione Turno",
                "verbose_name_plural": "Iscrizioni Turni",
                "ordering": ["-created_at"],
                "unique_together": {("turno", "volontario")},
            },
        ),
    ]
