# Generated by Django 4.2.7 on 2025-12-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shiftenrollment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="shiftenrollment",
            name="turno",
        ),
        migrations.RemoveField(
            model_name="shiftenrollment",
            name="volontario",
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["work_area", "nome"],
                "verbose_name": "Attività",
                "verbose_name_plural": "Attività",
            },
        ),
        migrations.RemoveField(
            model_name="activity",
            name="area",
        ),
        migrations.AddField(
            model_name="activity",
            name="work_area",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="users.workarea",
                verbose_name="Area di competenza",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Shift",
        ),
        migrations.DeleteModel(
            name="ShiftEnrollment",
        ),
    ]
