# Generated by Django 4.2.7 on 2025-12-01 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=200, verbose_name="Titolo")),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Da fare"),
                            ("in_progress", "In corso"),
                            ("done", "Completato"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("low", "Bassa"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completato il"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eliminato il"
                    ),
                ),
                (
                    "assegnato_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="todos_assegnati",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assegnato a",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="todos_creati",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "To-Do",
                "verbose_name_plural": "To-Do",
                "ordering": ["-priorita", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=200, verbose_name="Titolo")),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "file",
                    models.FileField(upload_to="documents/%Y/%m/", verbose_name="File"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("organigramma", "Organigramma"),
                            ("guida", "Guida/Manuale"),
                            ("modulo", "Modulo/Template"),
                            ("regolamento", "Regolamento"),
                            ("verbale", "Verbale"),
                            ("altro", "Altro"),
                        ],
                        default="altro",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "visibile_a",
                    models.CharField(
                        choices=[
                            ("tutti", "Tutti i volontari"),
                            ("admin", "Solo admin"),
                            ("segreteria", "Solo segreteria"),
                        ],
                        default="tutti",
                        max_length=50,
                        verbose_name="Visibile a",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Caricato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eliminato il"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Caricato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documenti",
                "ordering": ["-created_at"],
            },
        ),
    ]
